/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "GaoShan"
#property link      "kirc@yeah.net"

#property indicator_chart_window

extern bool showPriceLabel = TRUE;
double g_ihigh_80;
double g_ilow_88;
double g_iopen_96;
double g_iclose_104;
double gd_112;
double gd_120;
double gd_128;
double gd_136;
double gd_144;
double gd_152;
double gd_160;
double gd_168;
double gd_176;
double gd_184;
double gd_192;

int init() {
   return (0);
}

int deinit() {
   ObjectsDeleteAll(0, OBJ_TREND);
   ObjectsDeleteAll(0, OBJ_TEXT);
   return (0);
}

int start() {
   g_ihigh_80 = iHigh(NULL, PERIOD_D1, 1);
   g_ilow_88 = iLow(NULL, PERIOD_D1, 1);
   g_iopen_96 = iOpen(NULL, PERIOD_D1, 1);
   g_iclose_104 = iClose(NULL, PERIOD_D1, 1);
   gd_112 = NormalizeDouble((g_ihigh_80 + g_ilow_88 + g_iclose_104) / 3.0, Digits);
   gd_120 = NormalizeDouble(gd_112 + 20.0 * Point, Digits);
   gd_128 = NormalizeDouble(gd_112 + 40.0 * Point, Digits);
   gd_160 = NormalizeDouble(gd_112 - 20.0 * Point, Digits);
   gd_168 = NormalizeDouble(gd_112 - 40.0 * Point, Digits);
   gd_152 = NormalizeDouble(2.0 * gd_112 + (g_ihigh_80 - 2.0 * g_ilow_88) + 5.0 * Point, Digits);
   gd_192 = NormalizeDouble(2.0 * gd_112 - (2.0 * g_ihigh_80 - g_ilow_88) - 5.0 * Point, Digits);
   gd_144 = NormalizeDouble(gd_112 + (g_ihigh_80 - g_ilow_88) + 5.0 * Point, Digits);
   gd_184 = NormalizeDouble(gd_112 - (g_ihigh_80 - g_ilow_88) - 5.0 * Point, Digits);
   gd_136 = NormalizeDouble(gd_120 + gd_112 - g_ilow_88 - 5.0 * Point, Digits);
   gd_176 = NormalizeDouble(gd_160 + gd_112 - g_ihigh_80 + 5.0 * Point, Digits);
   int l_datetime_0 = TimeCurrent()+27200;
   int l_datetime_4 = TimeCurrent()+27200;
   int l_datetime_8 = TimeCurrent()+86400;
   if (showPriceLabel){
      creatTrendLineObj2("[WSS94] Line YH", l_datetime_4, g_ihigh_80, l_datetime_8, g_ihigh_80, Orange, 1, STYLE_DOT);
      createTextObj("[WSS94] Text YH", l_datetime_4, g_ihigh_80, StringConcatenate("[YesterdayHigh]", g_ihigh_80));
      creatTrendLineObj2("[WSS94] Line YL", l_datetime_4, g_ilow_88, l_datetime_8, g_ilow_88, Orange, 1, STYLE_DOT);
      createTextObj("[WSS94] Text YL", l_datetime_4, g_ilow_88, StringConcatenate("[YesterdayLow]", g_ilow_88));
   
      creatTrendLineObj2("[WSS94] Line YS", l_datetime_4, 0, l_datetime_4, 1, DarkGray, 1, STYLE_DOT);
      creatTrendLineObj2("[WSS94] Line YE", l_datetime_0, 0, l_datetime_0, 1, DarkGray, 1, STYLE_DOT);
      creatTrendLineObj("[WSS94] Line M", l_datetime_0, gd_112, l_datetime_8, Gray, 5);
      creatTrendLineObj("[WSS94] Line H1", l_datetime_0, gd_120, l_datetime_8, DarkBlue, 5);
      creatTrendLineObj("[WSS94] Line H2", l_datetime_0, gd_128, l_datetime_8, DarkBlue, 5);
      creatTrendLineObj("[WSS94] Line H3", l_datetime_0, gd_136, l_datetime_8, DarkBlue, 5);
      creatTrendLineObj("[WSS94] Line H4", l_datetime_0, gd_144, l_datetime_8, DarkBlue, 5);
      creatTrendLineObj("[WSS94] Line H5", l_datetime_0, gd_152, l_datetime_8, DarkBlue, 5);
      creatTrendLineObj("[WSS94] Line L1", l_datetime_0, gd_160, l_datetime_8, Maroon, 5);
      creatTrendLineObj("[WSS94] Line L2", l_datetime_0, gd_168, l_datetime_8, Maroon, 5);
      creatTrendLineObj("[WSS94] Line L3", l_datetime_0, gd_176, l_datetime_8, Maroon, 5);
      creatTrendLineObj("[WSS94] Line L4", l_datetime_0, gd_184, l_datetime_8, Maroon, 5);
      creatTrendLineObj("[WSS94] Line L5", l_datetime_0, gd_192, l_datetime_8, Maroon, 5);
   
      createTextObj("[WSS94] Text M", l_datetime_0, gd_112, StringConcatenate("[Middle Area]", gd_112));
      createTextObj("[WSS94] Text H1", l_datetime_0, gd_120, StringConcatenate("[Buy Start]", gd_120));
      createTextObj("[WSS94] Text H2", l_datetime_0, gd_128, StringConcatenate("[Buy End]", gd_128));
      createTextObj("[WSS94] Text H3", l_datetime_0, gd_136, StringConcatenate("[ReversalHigh]", gd_136));
      createTextObj("[WSS94] Text H4", l_datetime_0, gd_144, StringConcatenate("[OVERBOUGHT]", gd_144));
      createTextObj("[WSS94] Text H5", l_datetime_0, gd_152, StringConcatenate("[STOP BUY]", gd_152));
      createTextObj("[WSS94] Text L1", l_datetime_0, gd_160, StringConcatenate("[Sell Start]", gd_160));
      createTextObj("[WSS94] Text L2", l_datetime_0, gd_168, StringConcatenate("[Sell End]", gd_168));
      createTextObj("[WSS94] Text L3", l_datetime_0, gd_176, StringConcatenate("[ReversalLow]", gd_176));
      createTextObj("[WSS94] Text L4", l_datetime_0, gd_184, StringConcatenate("[OVERSOLD]", gd_184));
      createTextObj("[WSS94] Text L5", l_datetime_0, gd_192, StringConcatenate("[STOP SELL]", gd_192));
   }
   for (int li_12 = 1; li_12 < 20; li_12++) {
      if (showPriceLabel){
         creatTrendLineObj(StringConcatenate("[WSS94] Line HH", li_12), l_datetime_0, gd_120 + li_12 * Point, l_datetime_8, DarkBlue, 1);
         creatTrendLineObj(StringConcatenate("[WSS94] Line LL", li_12), l_datetime_0, gd_168 + li_12 * Point, l_datetime_8, Maroon, 1);
         creatTrendLineObj(StringConcatenate("[WSS94] Line MH", li_12), l_datetime_0, gd_112 + li_12 * Point, l_datetime_8, Gray, 1);
         creatTrendLineObj(StringConcatenate("[WSS94] Line ML", li_12), l_datetime_0, gd_112 - li_12 * Point, l_datetime_8, Gray, 1);
      }
   }
   return (0);
}

void creatTrendLineObj(string a_name_0, int a_datetime_8, double a_price_12, int a_datetime_20, color a_color_24, int a_width_28) {
   ObjectDelete(a_name_0);
   ObjectCreate(a_name_0, OBJ_TREND, 0, a_datetime_8, a_price_12, a_datetime_20, a_price_12);
   ObjectSet(a_name_0, OBJPROP_BACK, TRUE);
   ObjectSet(a_name_0, OBJPROP_COLOR, a_color_24);
   ObjectSet(a_name_0, OBJPROP_WIDTH, a_width_28);
}

void creatTrendLineObj2(string a_name_0, int a_datetime_8, double a_price_12, int a_datetime_20, double a_price_24, color a_color_32, int a_width_36, int a_style_40) {
   ObjectDelete(a_name_0);
   ObjectCreate(a_name_0, OBJ_TREND, 0, a_datetime_8, a_price_12, a_datetime_20, a_price_24);
   ObjectSet(a_name_0, OBJPROP_BACK, TRUE);
   ObjectSet(a_name_0, OBJPROP_COLOR, a_color_32);
   ObjectSet(a_name_0, OBJPROP_WIDTH, a_width_36);
   ObjectSet(a_name_0, OBJPROP_STYLE, a_style_40);
}

void createTextObj(string a_name_0, int a_datetime_8, double a_price_12, string a_text_20) {
   ObjectDelete(a_name_0);
   ObjectCreate(a_name_0, OBJ_TEXT, 0, a_datetime_8, a_price_12);
   ObjectSetText(a_name_0, a_text_20, 8, "Arial", White);
}
